name: Deploy image
inputs:
  service-account-key:
    required: true
  zone:
    required: true
    default: europe
  cluster:
    required: true
  image:
    required: true
runs:
  using: "composite"
  steps:
    - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
      with:
        cluster_name: ${{ inputs.cluster }}
        location: ${{ inputs.zone }}
        credentials: ${{ inputs.service-account-key }}

    - run: |
        sed -i 's|IMAGE|${{ inputs.image }}|' .deployments/deploy.yml
      shell: bash
    - if: ${{ startsWith(env.IMAGE_VERSION, 'dev-') }}
      run: sed -i 's/NAMESPACE/dev/' .deployments/deploy.yml
      shell: bash

    - if: ${{ startsWith(env.IMAGE_VERSION, 'rc-') }}
      run: sed -i 's/NAMESPACE/stage/' .deployments/deploy.yml
      shell: bash

    - if: ${{ startsWith(env.IMAGE_VERSION, 'v') }}
      run: sed -i 's/NAMESPACE/prod/' .deployments/deploy.yml
      shell: bash

    - run: | 
        namespace=$(grep namespace .deployments/deploy.yml | awk -F ':' '{print $2}')
        kubectl apply -f .deployments/deploy.yml
        kubectl rollout status deployments/go-deployment -n $namespace
#        kubectl get services -o wide
      shell: bash
