name: 'Push to gcr'
inputs:
  service-account-key:
    required: true
  project-id: 
    required: true
  image:
    required: true
runs:
  using: "composite"
  steps:
    - uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ inputs.service-account-key }}
        project_id: ${{ inputs.project-id }}
    - run: gcloud auth configure-docker -q
      shell: bash
    - run: docker push "${{ inputs.image }}"
      shell: bash
